export const FETCH_SOURCE_STATS = 'syslog/SideBar/FETCH_SOURCE_STATS';
export const FETCH_SOURCE_STATS_SUCCESS =
  'syslog/SideBar/FETCH_SOURCE_STATS_SUCCESS';
export const FETCH_SOURCE_STATS_FAIL = 'syslog/SideBar/FETCH_SOURCE_STATS_FAIL';

export const FETCH_GLOBAL_STATS = 'syslog/SideBar/FETCH_GLOBAL_STATS';
export const FETCH_GLOBAL_STATS_SUCCESS =
  'syslog/SideBar/FETCH_GLOBAL_STATS_SUCCESS';
export const FETCH_GLOBAL_STATS_FAIL = 'syslog/SideBar/FETCH_GLOBAL_STATS_FAIL';

export const FETCH_SOURCE_FILES = 'syslog/SideBar/FETCH_SOURCE_FILES';
export const FETCH_SOURCE_FILES_SUCCESS =
  'syslog/SideBar/FETCH_SOURCE_FILES_SUCCESS';
export const FETCH_SOURCE_FILES_FAIL = 'syslog/SideBar/FETCH_SOURCE_FILES_FAIL';

export const FETCH_SOURCE_ARCHIVES = 'syslog/SideBar/FETCH_SOURCE_ARCHIVES';
export const FETCH_SOURCE_ARCHIVES_SUCCESS =
  'syslog/SideBar/FETCH_SOURCE_ARCHIVES_SUCCESS';
export const FETCH_SOURCE_ARCHIVES_FAIL =
  'syslog/SideBar/FETCH_SOURCE_ARCHIVES_FAIL';
