export const TOGGLE_AUTO_DISCOVER_BUTTON =
  'syslog/SideBar/TOGGLE_AUTO_DISCOVER_BUTTON';
export const TOGGLE_SOURCE_AUTO_DISCOVER_BUTTON =
  'syslog/SideBar/TOGGLE_SOURCE_AUTO_DISCOVER_BUTTON';

export const OPEN_SYSLOG_SOURCE_ADD_FORM =
  'syslog/SideBar/OPEN_SYSLOG_SOURCE_ADD_FORM';

export const CLOSE_SYSLOG_SOURCE_ADD_FORM =
  'syslog/SideBar/CLOSE_SYSLOG_SOURCE_ADD_FORM';

export const OPEN_LISTENING_PORT_MODAL =
  'syslog/SideBar/OPEN_LISTENING_PORT_MODAL';

export const CLOSE_LISTENING_PORT_MODAL =
  'syslog/SideBar/CLOSE_LISTENING_PORT_MODAL';

export const FETCH_SOURCE_LIST = 'syslog/SideBar/FETCH_SOURCE_LIST';

export const FETCH_SOURCE_LIST_SUCCESS =
  'syslog/SideBar/FETCH_SOURCE_LIST_SUCCESS';

export const FETCH_SOURCE_LIST_FAIL = 'syslog/SideBar/FETCH_SOURCE_LIST_FAIL';
