export const TOGGLE_AUTO_DISCOVER = 'syslog/SideBar/TOGGLE_AUTO_DISCOVER';
export const TOGGLE_SOURCE_AUTO_DISCOVER =
  'syslog/SideBar/TOGGLE_SOURCE_AUTO_DISCOVER';
export const TOGGLE_SOURCE_AUTO_DISCOVER_SUCCESS =
  'syslog/SideBar/TOGGLE_SOURCE_AUTO_DISCOVER_SUCCESS';
export const TOGGLE_SOURCE_AUTO_DISCOVER_FAIL =
  'syslog/SideBar/TOGGLE_SOURCE_AUTO_DISCOVER_FAIL';

export const OPEN_SYSLOG_SOURCE_ADD_FORM =
  'syslog/SideBar/OPEN_SYSLOG_SOURCE_ADD_FORM';

export const CLOSE_SYSLOG_SOURCE_ADD_FORM =
  'syslog/SideBar/CLOSE_SYSLOG_SOURCE_ADD_FORM';

export const OPEN_SOURCE_EDITOR = 'syslog/SideBar/OPEN_SOURCE_EDITOR';

export const CLOSE_SOURCE_EDITOR = 'syslog/SideBar/CLOSE_SOURCE_EDITOR';

export const OPEN_LISTENING_PORT_MODAL =
  'syslog/SideBar/OPEN_LISTENING_PORT_MODAL';

export const CLOSE_LISTENING_PORT_MODAL =
  'syslog/SideBar/CLOSE_LISTENING_PORT_MODAL';

export const FETCH_SOURCE_LIST = 'syslog/SideBar/FETCH_SOURCE_LIST';

export const FETCH_SOURCE_LIST_SUCCESS =
  'syslog/SideBar/FETCH_SOURCE_LIST_SUCCESS';

export const FETCH_SOURCE_LIST_FAIL = 'syslog/SideBar/FETCH_SOURCE_LIST_FAIL';

export const ADD_OR_UPDATE_SOURCE = 'syslog/SideBar/ADD_OR_UPDATE_SOURCE';
export const ADD_OR_UPDATE_SOURCE_SUCCESS =
  'syslog/SideBar/ADD_OR_UPDATE_SOURCE_SUCCESS';
export const ADD_OR_UPDATE_SOURCE_FAIL =
  'syslog/SideBar/ADD_OR_UPDATE_SOURCE_FAIL';

export const DELETE_SOURCE = 'syslog/SideBar/DELETE_SOURCE';
export const DELETE_SOURCE_SUCCESS = 'syslog/SideBar/DELETE_SOURCE_SUCCESS';
export const DELETE_SOURCE_FAIL = 'syslog/SideBar/DELETE_SOURCE_FAIL';
