export const LOGIN = 'syslog/HomePage/LOGIN';

export const FETCH_GLOBAL_SETTINGS =
  'syslog/HomePage/FETCH_GLOBAL_SETTINGS';

export const FETCH_GLOBAL_SETTINGS_SUCCESS =
  'syslog/HomePage/FETCH_GLOBAL_SETTINGS_SUCCESS';

export const FETCH_GLOBAL_SETTINGS_FAIL =
  'syslog/HomePage/FETCH_GLOBAL_SETTINGS_FAIL';

export const UPDATE_GLOBAL_SETTINGS =
  'syslog/HomePage/UPDATE_GLOBAL_SETTINGS';

export const UPDATE_GLOBAL_SETTINGS_SUCCESS =
  'syslog/HomePage/UPDATE_GLOBAL_SETTINGS_SUCCESS';

export const UPDATE_GLOBAL_SETTINGS_FAIL =
  'syslog/HomePage/UPDATE_GLOBAL_SETTINGS_FAIL';

export const FETCH_AND_UPDATE_GLOBAL_SETTINGS =
  'syslog/HomePage/FETCH_AND_UPDATE_GLOBAL_SETTINGS';

export const FETCH_AND_UPDATE_GLOBAL_SETTINGS_SUCCESS =
  'syslog/HomePage/FETCH_AND_UPDATE_GLOBAL_SETTINGS_SUCCESS';

export const FETCH_AND_UPDATE_GLOBAL_SETTINGS_FAIL =
  'syslog/HomePage/FETCH_AND_UPDATE_GLOBAL_SETTINGS_FAIL';
